### ISSUE TITLE
OpenFaaS stack template shows "Deployment error"

### ISSUE THREAD

**Issue by BurtonR** [portainer/templates#86] opened 2018-02-07 19:25 UTC
Using the demo site: http://demo.portainer.io/#/templates/

Deploying the OpenFaaS template results in an error and the stack is not deployed.

![screenshot from 2018-02-07 13-06-33](https://user-images.githubusercontent.com/12687192/35936857-1ee75d7e-0c0a-11e8-8e18-1e18497b2b64.png)

Also, it still shows in the "stacks" view, although no services or tasks are listed in the "Stack details" view

**Comment by BurtonR** [comment] 2018-02-07 20:11
Looking into it a little further, I see the OpenFaaS `docker-compose.yml` file makes a reference to a folder/file that is included in the openfaas repo (where the docker-compose file is pulled).

Is there a way for Portainer to pull that file as well as the compose file? when the template is deployed?

**Comment by deviantony** [comment] 2018-02-09 09:38
Yup, looks like it's related to https://github.com/openfaas/faas/blob/master/docker-compose.yml#L257-L263  introduced via https://github.com/openfaas/faas/commit/f954bf0733c34d130dd93c5176a774820252b9f7#diff-4e5e90c6228fd48698d074241c2ba760R257

Portainer already clone the repository where the stack file is located but the fact that this stack is using a relative path is causing an issue.

I believe we can fix this by executing the `docker stack deploy` command inside the cloned repository. I'll open an issue in the Portainer repository.

**Comment by deviantony** [comment] 2018-02-09 09:56
Fixed via https://github.com/portainer/portainer/pull/1648

I'll keep this issue open until the next Portainer release, you can use our development build in the meantime (`portainer/portainer:develop)`.

**Comment by BurtonR** [comment] 2018-02-10 15:03
Just tried it out locally using the `portainer/portainer:develop` image. Works like a champ! Thanks for the quick response and resolution! 💯 

Feel free to close this issue

**Comment by deviantony** [comment] 2018-03-14 21:55
Closing as the fix has been released.

**Closed by deviantony** 2018-03-14 21:55 UTC

**Comment by steevegldev** [comment] 2019-01-16 17:24
Can reproduce with portainer/portainer:latest@sha256:339b6486297050179418c886272f3262794b54513008a7f8e747c5e8f330338d
and portainer/portainer:develop@sha256:bdbc972575437bfdc105d57c1caadbd17de8c58fb6da2bd0f7250e024bfec0ae
